#!/bin/bash
echo "This is a bash script that runs muscle!"

infile='data/co1.fa'
outfile='out.phy'
jobname='tree1'
mu_maxiters=100

cat $infile | sed"s/[|]//g" |  awk -F " " '{if($2 ~ /[A-Za-z_0-9]/){print ">" $2}else{print $0}}' > trim.fa

wcin=$(cat trim.fa | wc -m)

./muscle -in trim.fa -phyiout $outfile -maxiters $mu_maxiters

wcout=$(cat $outfile | wc -m)

wcchange=$(expr $wcout - $wcin)

echo "Muscle added $wcchange characters.\n"


./raxml -f a -p 12345 -x 12345 -N 100 -s out.phy -m GTRCAT -n boot3 -T2
./raxml -f b -t ref -z RAxML_bootstrap.boot1 -m GTRCAT -n consensus -T2

echo "RAxML Finished!"

